[profile.default]
src = "contracts"
test = "contracts/tests"
script = "contracts/foundry_script"
out = "artifacts/forge"
cache = true
cache_path = "cache/forge"
optimizer = true
optimizer_runs = 200
via_ir = true
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "forge-std=node_modules/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
